-- MySQL Script generated by MySQL Workbench
-- Wed Sep 30 22:29:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema artistica_dali
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema artistica_dali
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `artistica_dali` DEFAULT CHARACTER SET utf8 ;
USE `artistica_dali` ;

-- -----------------------------------------------------
-- Table `artistica_dali`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artistica_dali`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(70) NOT NULL,
  `telefono` VARCHAR(30) NULL,
  `calle` VARCHAR(45) NULL,
  `numero` INT NULL,
  `dpto` VARCHAR(10) NULL,
  `cp` VARCHAR(15) NULL,
  `provincia` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NULL,
  `rol` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artistica_dali`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artistica_dali`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artistica_dali`.`subcategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artistica_dali`.`subcategories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `categoria_idx` (`categoria_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `artistica_dali`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artistica_dali`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artistica_dali`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  `descuento` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `subcategoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `subcategory_idx` (`subcategoria_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `subcategory`
    FOREIGN KEY (`subcategoria_id`)
    REFERENCES `artistica_dali`.`subcategories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artistica_dali`.`product_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artistica_dali`.`product_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `producto_id` INT NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `producto_id_idx` (`producto_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `producto_id`
    FOREIGN KEY (`producto_id`)
    REFERENCES `artistica_dali`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artistica_dali`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artistica_dali`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_id_carrito_idx` (`usuario_id` ASC),
  INDEX `producto_id_carrito_idx` (`producto_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `usuario_id_carrito`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `artistica_dali`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `producto_id_carrito`
    FOREIGN KEY (`producto_id`)
    REFERENCES `artistica_dali`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artistica_dali`.`purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artistica_dali`.`purchases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_id_compra_idx` (`usuario_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `usuario_id_compra`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `artistica_dali`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artistica_dali`.`purchase_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artistica_dali`.`purchase_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `compra_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `venta_id_idx` (`compra_id` ASC),
  INDEX `producto_id_compra_idx` (`producto_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `compra_id`
    FOREIGN KEY (`compra_id`)
    REFERENCES `artistica_dali`.`purchases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `producto_id_compra`
    FOREIGN KEY (`producto_id`)
    REFERENCES `artistica_dali`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
